included:
  - iOS/Sources
  - watchOS/Sources
  - Shared/Sources

excluded:
  - .build
  - DerivedData

disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - explicit_init

line_length:
  warning: 140
  error: 200

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 600
  error: 1000
